// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SocialApis.Models;

public partial class like
{
    [Key]
    public int like_id { get; set; }

    public int post_id { get; set; }

    public int user_id { get; set; }

    public DateTime? created_at { get; set; }

    [ForeignKey("post_id")]
    [InverseProperty("likes")]
    public virtual post post { get; set; }

    [ForeignKey("user_id")]
    [InverseProperty("likes")]
    public virtual user user { get; set; }
}