// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SocialApis.Models;

public partial class post
{
    [Key]
    public int post_id { get; set; }

    public int user_id { get; set; }

    [Required]
    [Column(TypeName = "text")]
    public string content { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? created_at { get; set; }

    [InverseProperty("post")]
    public virtual ICollection<comment> comments { get; } = new List<comment>();

    [InverseProperty("post")]
    public virtual ICollection<like> likes { get; } = new List<like>();

    [ForeignKey("user_id")]
    [InverseProperty("posts")]
    public virtual user user { get; set; }
}