// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace SocialApis.Models;

public partial class SocialDbContext : DbContext
{
    public SocialDbContext(DbContextOptions<SocialDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<comment> comments { get; set; }

    public virtual DbSet<like> likes { get; set; }

    public virtual DbSet<post> posts { get; set; }

    public virtual DbSet<user> users { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<comment>(entity =>
        {
            entity.HasKey(e => e.comment_id).HasName("PK__comments__E7957687E20C5BD0");

            entity.Property(e => e.comment_id).ValueGeneratedNever();
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.post).WithMany(p => p.comments).HasConstraintName("FK__comments__post_i__49C3F6B7");

            entity.HasOne(d => d.user).WithMany(p => p.comments)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__comments__user_i__4AB81AF0");
        });

        modelBuilder.Entity<like>(entity =>
        {
            entity.HasKey(e => e.like_id).HasName("PK__likes__992C79300A9B653F");

            entity.Property(e => e.like_id).ValueGeneratedNever();
            entity.Property(e => e.created_at).HasDefaultValueSql("(getutcdate())");

            entity.HasOne(d => d.post).WithMany(p => p.likes).HasConstraintName("FK__likes__post_id__4E88ABD4");

            entity.HasOne(d => d.user).WithMany(p => p.likes)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__likes__user_id__4F7CD00D");
        });

        modelBuilder.Entity<post>(entity =>
        {
            entity.HasKey(e => e.post_id).HasName("PK__posts__3ED78766DB2EFB18");

            entity.Property(e => e.post_id).ValueGeneratedNever();
            entity.Property(e => e.created_at).HasDefaultValueSql("(getdate())");

            entity.HasOne(d => d.user).WithMany(p => p.posts).HasConstraintName("FK__posts__user_id__45F365D3");
        });

        modelBuilder.Entity<user>(entity =>
        {
            entity.HasKey(e => e.user_id).HasName("PK__users__B9BE370F55BD7D42");

            entity.Property(e => e.user_id).ValueGeneratedNever();
            entity.Property(e => e.created_at).HasDefaultValueSql("(getdate())");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}