// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace SocialApis.Models;

public partial class user
{
    [Key]
    public int user_id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string username { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string email { get; set; }

    [Required]
    [StringLength(100)]
    [Unicode(false)]
    public string password { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? created_at { get; set; }

    [InverseProperty("user")]
    public virtual ICollection<comment> comments { get; } = new List<comment>();

    [InverseProperty("user")]
    public virtual ICollection<like> likes { get; } = new List<like>();

    [InverseProperty("user")]
    public virtual ICollection<post> posts { get; } = new List<post>();
}